name: build-linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: git submodules
        run: git submodule update --init --recursive

      - name: cmake init
        run: |
          mkdir -p build
          cd build
          cmake ..
      
      - name: cmake build
        run: |
          cd build
          cmake --build .

      # - name: run
      #   run: |
      #     cd build
      #     ./pacman

      - name: test
        run: |
          cd build
          ctest --output-on-failure